--------------------------------------------------------
--  DDL for Table MAK_DAMAGE_RATE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_DAMAGE_RATE" 
   (	"LOC" VARCHAR2(50 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR), 
	"QB" VARCHAR2(14 CHAR), 
	"MAXHRSPERDAY" NUMBER, 
	"MAXCAP" NUMBER, 
	"MINCAP" NUMBER, 
	"YIELD" NUMBER, 
	"LAT" FLOAT(126), 
	"LON" FLOAT(126), 
	"LOC_TYPE" NUMBER(*,0), 
	"COMPANYID" VARCHAR2(50 CHAR), 
	"POSTALCODE" VARCHAR2(10 CHAR), 
	"COUNTRY" VARCHAR2(20 CHAR), 
	"U_LOCTYPE" VARCHAR2(50 CHAR), 
	"U_CITY" VARCHAR2(50 CHAR), 
	"U_GEOCODE" VARCHAR2(50 CHAR), 
	"U_3DIGITZIP" VARCHAR2(50 CHAR), 
	"U_STATE" VARCHAR2(50 CHAR), 
	"U_AREA" VARCHAR2(50 CHAR), 
	"U_REGION" VARCHAR2(50 CHAR), 
	"U_PARENT" VARCHAR2(50 CHAR), 
	"U_SUBAFFIL" VARCHAR2(50 CHAR), 
	"U_GRANDPARENT" VARCHAR2(50 CHAR), 
	"U_AFFIL" VARCHAR2(50 CHAR), 
	"U_CUSTTYPE" VARCHAR2(50 CHAR), 
	"U_CGROUP" VARCHAR2(50 CHAR), 
	"U_INDUSTRY" VARCHAR2(50 CHAR), 
	"U_MKTSECTOR" VARCHAR2(50 CHAR), 
	"U_MAX_SRC" NUMBER(10,0), 
	"U_MAX_DIST" NUMBER(10,0), 
	"U_PRODUCT_SPECIALITY" VARCHAR2(50 CHAR), 
	"U_PLANT_NETWORK_TYPE" VARCHAR2(20 CHAR), 
	"U_SALES_SECTOR" VARCHAR2(100 CHAR), 
	"U_TERRITORY" VARCHAR2(100 CHAR), 
	"U_PLANTGROUP" VARCHAR2(50 CHAR), 
	"U_CLOSINGDATE" DATE, 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 CHAR), 
	"U_RUNEW_CUST" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
